services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: ""
    startCommand: "uvicorn JEWELLERY_FASTAPI.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: ENV
        value: production

